DROP TABLE CLIENTE IF EXISTS;
CREATE TABLE CLIENTE (

id INT,
nombre VARCHAR(150) NOT NULL,
apellido VARCHAR(150) NOT NULL,
dni INT NOT NULL,
);

DROP TABLE PRODUCTOS IF EXISTS;
CREATE TABLE PRODUCTOS (
id INT,
nombre VARCHAR(150) NOT NULL,
marca VARCHAR(150) NOT NULL,
cantidad INT NOT NULL,
);

DROP TABLE VENTA IF EXISTS;
CREATE TABLE VENTA (
id INT,
comprobante INT NOT NULL,
mail_de_comprador VARCHAR(150) NOT NULL,
seguimiento INT NOT NULL,
);
